\begin{syntax}
  alpha  ::= "a" - "z" | "A" - "Z"
  \
  digit ::= "0" - "9"
  \
  suffix ::= alpha | digit | "'" | "_"
  \
  lident ::= ("a" - "z") suffix* | "_" suffix+
  \
  uident ::= ("A" - "Z") suffix*
  \
  qident ::= "'" ("a" - "z") suffix* %
\end{syntax}
