\begin{syntax}
  type-spec ::= "(*@" type-spec-content* "*)"
  \
  type-spec-content ::= "ephemeral" ;
                    | "mutable"? "model" lident-ext ":" type ;
                    | "invariant" term
\end{syntax}