\begin{syntax}
  use-module ::= "(*@" "use" uqualid ("as" uqualid)? "*)"
  \
  predicate-def ::= "(*@" "predicate" lident-ext param+ ("=" term)? function-spec* "*)" ;
                | ( "(*@" function-spec "*)" )*
  \
  function-decl ::= "(*@" "function" lident-ext param* ":" type ("=" term)? function-spec* "*)" ;
                | ( "(*@" function-spec "*)" )*
  \
  axiom ::= "(*@" "axiom" lident ":" term "*)"
\end{syntax}

\begin{syntax}
  function-spec ::= "coercion" ; set function as coercion
                | "requires" term             ; precondition
                | "ensures" term              ; postcondition
  \
\end{syntax}
