\begin{syntax}
  op-char-1 ::= "=" | "<" | ">" | "~" ;
  \
  op-char-2 ::= "+" | "-" ;
  \
  op-char-3 ::= "*" | "/" | "\" | "%" ;
  \
  op-char-4 ::= "!" | "$" | "&" | "?" | "@" | "^" | "." | ":" | "|" | "#" ;
  \
  op-char-1234 ::= op-char-1 | op-char-2 | op-char-3 | op-char-4 ;
  \
  op-char-234 ::= op-char-2 | op-char-3 | op-char-4 ;
  \
  op-char-34 ::= op-char-3 | op-char-4 ;
  \
  infix-op-1 ::= op-char-1234* op-char-1 op-char-1234*      ;
  \
  infix-op-2 ::= op-char-234* op-char-2 op-char-234*      ;
  \
  infix-op-3 ::= op-char-34* op-char-3 op-char-34*      ;
  \
  infix-op-4 ::= op-char-4+      ;
  \
  prefix-op ::= op-char-1234+      ;
  \
  tight-op ::= ("!" | "?") op-char-4*      ; %
\end{syntax}
