\begin{syntax}
  term ::= ...  ; see Fig.~\ref{fig:bnf:term1} and \ref{fig:bnf:term2}
    | "if" term "then" term "else" term     ; conditional
    | "match" term "with" term-case+ "end"  ; pattern matching
    | "let" pattern "=" term "in" term      ; let-binding
    | "let" "(" ident-op ")" "=" term "in" term  ; let-binding ident-op
    | "fun" param+ "->" term                ; unnamed mapping
  \
  term-case ::= "|" pattern "->" term
  \
  pattern ::=
      binder                            ; variable or `\texttt{\_}'
    | "()"                              ; empty tuple
    | "{" (lqualid "=" pattern ";")+ "}"  ; record pattern
    | uqualid pattern*                  ; constructor
    | pattern "as" bound-var            ; named sub-pattern
    | pattern "," pattern               ; tuple pattern
    | pattern "|" pattern               ; ``or'' pattern
  \
  param ::=
      type-arg                 ; unnamed typed
    | binder                   ; (un)named untyped
    | "(" type ")"             ; unnamed typed
    | "(" binder ")"           ; (un)named untyped
    | "(" binder+ ":" type ")" ; multi-variable typed %
\end{syntax}
