name: changelog

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, labeled, unlabeled ]

jobs:
  build:
    runs-on: ubuntu-latest

    if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-changelog-needed') }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: git diff
      env:
        BASE_REF: ${{ github.event.pull_request.base.ref }}
      run: |
        ! git diff --exit-code remotes/origin/$BASE_REF -- CHANGES.md
